/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);
void BOARD_InitSemcPins(void);
void BOARD_InitSDMMCPins(void);
void BOARD_InitLCDPins(void);
void BOARD_InitSAIPins(void);

/* GPIO_AD_B1_10 (coord L13), LED_R */
#define BOARD_INITPINS_LED_R_GPIO                                          GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_LED_R_PORT                                          GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_LED_R_GPIO_PIN                                        26U   /*!< GPIO1 pin index: 26 */
#define BOARD_INITPINS_LED_R_PIN_NAME                              GPIO_AD_B1_10   /*!< Pin name */
#define BOARD_INITPINS_LED_R_LABEL                                       "LED_R"   /*!< Label */
#define BOARD_INITPINS_LED_R_NAME                                        "LED_R"   /*!< Identifier name */
#define BOARD_INITPINS_LED_R_DIRECTION                  kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_AD_B1_09 (coord M13), LED_G */
#define BOARD_INITPINS_LED_G_GPIO                                          GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_LED_G_PORT                                          GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_LED_G_GPIO_PIN                                        25U   /*!< GPIO1 pin index: 25 */
#define BOARD_INITPINS_LED_G_PIN_NAME                              GPIO_AD_B1_09   /*!< Pin name */
#define BOARD_INITPINS_LED_G_LABEL                                       "LED_G"   /*!< Label */
#define BOARD_INITPINS_LED_G_NAME                                        "LED_G"   /*!< Identifier name */
#define BOARD_INITPINS_LED_G_DIRECTION                  kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_AD_B1_05 (coord K12), LED_B */
#define BOARD_INITPINS_LED_B_GPIO                                          GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_LED_B_PORT                                          GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_LED_B_GPIO_PIN                                        21U   /*!< GPIO1 pin index: 21 */
#define BOARD_INITPINS_LED_B_PIN_NAME                              GPIO_AD_B1_05   /*!< Pin name */
#define BOARD_INITPINS_LED_B_LABEL                                       "LED_B"   /*!< Label */
#define BOARD_INITPINS_LED_B_NAME                                        "LED_B"   /*!< Identifier name */
#define BOARD_INITPINS_LED_B_DIRECTION                  kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_AD_B1_13 (coord H11), NRF_IRQ */
#define BOARD_INITPINS_NRF_IRQ_GPIO                                        GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_NRF_IRQ_PORT                                        GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_NRF_IRQ_GPIO_PIN                                      29U   /*!< GPIO1 pin index: 29 */
#define BOARD_INITPINS_NRF_IRQ_PIN_NAME                            GPIO_AD_B1_13   /*!< Pin name */
#define BOARD_INITPINS_NRF_IRQ_LABEL                                   "NRF_IRQ"   /*!< Label */
#define BOARD_INITPINS_NRF_IRQ_NAME                                    "NRF_IRQ"   /*!< Identifier name */
#define BOARD_INITPINS_NRF_IRQ_DIRECTION                 kPIN_MUX_DirectionInput   /*!< Direction */

/* GPIO_AD_B1_14 (coord G12), NRF_MISO */
#define BOARD_INITPINS_NRF_MISO_GPIO                                       GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_NRF_MISO_PORT                                       GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_NRF_MISO_GPIO_PIN                                     30U   /*!< GPIO1 pin index: 30 */
#define BOARD_INITPINS_NRF_MISO_PIN_NAME                           GPIO_AD_B1_14   /*!< Pin name */
#define BOARD_INITPINS_NRF_MISO_LABEL                                 "NRF_MISO"   /*!< Label */
#define BOARD_INITPINS_NRF_MISO_NAME                                  "NRF_MISO"   /*!< Identifier name */
#define BOARD_INITPINS_NRF_MISO_DIRECTION                kPIN_MUX_DirectionInput   /*!< Direction */

/* GPIO_AD_B1_12 (coord H12), NRF_MOSI */
#define BOARD_INITPINS_NRF_MOSI_GPIO                                       GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_NRF_MOSI_PORT                                       GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_NRF_MOSI_GPIO_PIN                                     28U   /*!< GPIO1 pin index: 28 */
#define BOARD_INITPINS_NRF_MOSI_PIN_NAME                           GPIO_AD_B1_12   /*!< Pin name */
#define BOARD_INITPINS_NRF_MOSI_LABEL                                 "NRF_MOSI"   /*!< Label */
#define BOARD_INITPINS_NRF_MOSI_NAME                                  "NRF_MOSI"   /*!< Identifier name */
#define BOARD_INITPINS_NRF_MOSI_DIRECTION               kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_AD_B1_15 (coord J14), NRF_SCK */
#define BOARD_INITPINS_NRF_SCK_GPIO                                        GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_NRF_SCK_PORT                                        GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_NRF_SCK_GPIO_PIN                                      31U   /*!< GPIO1 pin index: 31 */
#define BOARD_INITPINS_NRF_SCK_PIN_NAME                            GPIO_AD_B1_15   /*!< Pin name */
#define BOARD_INITPINS_NRF_SCK_LABEL                                   "NRF_SCK"   /*!< Label */
#define BOARD_INITPINS_NRF_SCK_NAME                                    "NRF_SCK"   /*!< Identifier name */
#define BOARD_INITPINS_NRF_SCK_DIRECTION                kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_AD_B1_11 (coord J13), NRF_CSN */
#define BOARD_INITPINS_NRF_CSN_GPIO                                        GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_NRF_CSN_PORT                                        GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_NRF_CSN_GPIO_PIN                                      27U   /*!< GPIO1 pin index: 27 */
#define BOARD_INITPINS_NRF_CSN_PIN_NAME                            GPIO_AD_B1_11   /*!< Pin name */
#define BOARD_INITPINS_NRF_CSN_LABEL                                   "NRF_CSN"   /*!< Label */
#define BOARD_INITPINS_NRF_CSN_NAME                                    "NRF_CSN"   /*!< Identifier name */
#define BOARD_INITPINS_NRF_CSN_DIRECTION                kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_AD_B1_04 (coord L12), NRF_CE */
#define BOARD_INITPINS_NRF_CE_GPIO                                         GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_NRF_CE_PORT                                         GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_NRF_CE_GPIO_PIN                                       20U   /*!< GPIO1 pin index: 20 */
#define BOARD_INITPINS_NRF_CE_PIN_NAME                             GPIO_AD_B1_04   /*!< Pin name */
#define BOARD_INITPINS_NRF_CE_LABEL                                     "NRF_CE"   /*!< Label */
#define BOARD_INITPINS_NRF_CE_NAME                                      "NRF_CE"   /*!< Identifier name */
#define BOARD_INITPINS_NRF_CE_DIRECTION                 kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_AD_B1_08 (coord H13), BQ_OTG */
#define BOARD_INITPINS_BQ_OTG_GPIO                                         GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_BQ_OTG_PORT                                         GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_BQ_OTG_GPIO_PIN                                       24U   /*!< GPIO1 pin index: 24 */
#define BOARD_INITPINS_BQ_OTG_PIN_NAME                             GPIO_AD_B1_08   /*!< Pin name */
#define BOARD_INITPINS_BQ_OTG_LABEL                                     "BQ_OTG"   /*!< Label */
#define BOARD_INITPINS_BQ_OTG_NAME                                      "BQ_OTG"   /*!< Identifier name */
#define BOARD_INITPINS_BQ_OTG_DIRECTION                 kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_AD_B1_07 (coord K10), BQ_INT */
#define BOARD_INITPINS_BQ_INT_GPIO                                         GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_BQ_INT_PORT                                         GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_BQ_INT_GPIO_PIN                                       23U   /*!< GPIO1 pin index: 23 */
#define BOARD_INITPINS_BQ_INT_PIN_NAME                             GPIO_AD_B1_07   /*!< Pin name */
#define BOARD_INITPINS_BQ_INT_LABEL                                     "BQ_INT"   /*!< Label */
#define BOARD_INITPINS_BQ_INT_NAME                                      "BQ_INT"   /*!< Identifier name */
#define BOARD_INITPINS_BQ_INT_DIRECTION                  kPIN_MUX_DirectionInput   /*!< Direction */

/* GPIO_AD_B1_06 (coord J12), SD_CK */
#define BOARD_INITPINS_SD_CK_GPIO                                          GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_SD_CK_PORT                                          GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_SD_CK_GPIO_PIN                                        22U   /*!< GPIO1 pin index: 22 */
#define BOARD_INITPINS_SD_CK_PIN_NAME                              GPIO_AD_B1_06   /*!< Pin name */
#define BOARD_INITPINS_SD_CK_LABEL                                       "SD_CK"   /*!< Label */
#define BOARD_INITPINS_SD_CK_NAME                                        "SD_CK"   /*!< Identifier name */
#define BOARD_INITPINS_SD_CK_DIRECTION                   kPIN_MUX_DirectionInput   /*!< Direction */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
