/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.38                          *
*        Compiled Nov 24 2016, 16:57:40                              *
*        (c) 2016 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "fsl_debug_console.h"
#include "fsl_common.h"
#include "fsl_sd.h"
#include "fsl_sd_disk.h"

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "list.h"
#include "semphr.h"

#include "include.h"
#include "DIALOG.h"
#include "MainTask.h"
#include "bq25895.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_1 (GUI_ID_USER + 0x02)
#define ID_BUTTON_2 (GUI_ID_USER + 0x03)
#define ID_BUTTON_3 (GUI_ID_USER + 0x04)
#define ID_BUTTON_4 (GUI_ID_USER + 0x05)
#define ID_TEXT_0 (GUI_ID_USER + 0x06)
#define ID_TEXT_1 (GUI_ID_USER + 0x07)
#define ID_TEXT_2 (GUI_ID_USER + 0x08)
#define ID_TEXT_3 (GUI_ID_USER + 0x09)
#define ID_TEXT_4 (GUI_ID_USER + 0x0A)
#define ID_TEXT_5 (GUI_ID_USER + 0x0B)
#define ID_TEXT_6 (GUI_ID_USER + 0x0C)
#define ID_TEXT_7 (GUI_ID_USER + 0x0D)
#define ID_TEXT_8 (GUI_ID_USER + 0x0E)
#define ID_TEXT_9 (GUI_ID_USER + 0x0F)
#define ID_TEXT_10 (GUI_ID_USER + 0x10)
#define ID_TEXT_11 (GUI_ID_USER + 0x11)
#define ID_DROPDOWN_0            (GUI_ID_USER + 0x12)
#define ID_DROPDOWN_1            (GUI_ID_USER + 0x13)
#define ID_DROPDOWN_2            (GUI_ID_USER + 0x14)
#define ID_DROPDOWN_3            (GUI_ID_USER + 0x15)
#define ID_DROPDOWN_4            (GUI_ID_USER + 0x16)
#define ID_DROPDOWN_5            (GUI_ID_USER + 0x17)
#define ID_DROPDOWN_6            (GUI_ID_USER + 0x18)
#define ID_DROPDOWN_7            (GUI_ID_USER + 0x19)
#define ID_DROPDOWN_8            (GUI_ID_USER + 0x1A)
#define ID_DROPDOWN_9            (GUI_ID_USER + 0x1B)
#define ID_DROPDOWN_10           (GUI_ID_USER + 0x1C)
#define ID_TEXT_12           (GUI_ID_USER + 0x1D)
#define ID_TEXT_13           (GUI_ID_USER + 0x1E)
#define ID_TEXT_14           (GUI_ID_USER + 0x1F)
#define ID_TEXT_15           (GUI_ID_USER + 0x20)
#define ID_TEXT_16           (GUI_ID_USER + 0x21)
#define ID_TEXT_17           (GUI_ID_USER + 0x22)
#define ID_TEXT_18           (GUI_ID_USER + 0x23)
#define ID_TEXT_19           (GUI_ID_USER + 0x24)
#define ID_TEXT_20           (GUI_ID_USER + 0x25)
#define ID_TEXT_21           (GUI_ID_USER + 0x26)
#define ID_DROPDOWN_11           (GUI_ID_USER + 0x27)
#define ID_DROPDOWN_12           (GUI_ID_USER + 0x28)
#define ID_DROPDOWN_13           (GUI_ID_USER + 0x29)
#define ID_DROPDOWN_14           (GUI_ID_USER + 0x2A)
#define ID_DROPDOWN_15           (GUI_ID_USER + 0x2B)
#define ID_DROPDOWN_16           (GUI_ID_USER + 0x2C)
#define ID_DROPDOWN_17           (GUI_ID_USER + 0x2D)
#define ID_DROPDOWN_18           (GUI_ID_USER + 0x2E)
#define ID_DROPDOWN_19           (GUI_ID_USER + 0x2F)
#define ID_DROPDOWN_20           (GUI_ID_USER + 0x30)
#define ID_TEXT_22           (GUI_ID_USER + 0x31)
#define ID_TEXT_23           (GUI_ID_USER + 0x32)
#define ID_TEXT_24           (GUI_ID_USER + 0x33)
#define ID_TEXT_25           (GUI_ID_USER + 0x34)
#define ID_TEXT_26           (GUI_ID_USER + 0x35)
#define ID_TEXT_27           (GUI_ID_USER + 0x36)
#define ID_TEXT_28           (GUI_ID_USER + 0x37)
#define ID_TEXT_29           (GUI_ID_USER + 0x38)
#define ID_TEXT_30           (GUI_ID_USER + 0x39)
#define ID_TEXT_31           (GUI_ID_USER + 0x3A)
#define ID_TEXT_32           (GUI_ID_USER + 0x3B)
#define ID_TEXT_33           (GUI_ID_USER + 0x3C)
#define ID_EDIT_0           (GUI_ID_USER + 0x3D)
#define ID_EDIT_1           (GUI_ID_USER + 0x3E)
#define ID_EDIT_2           (GUI_ID_USER + 0x3F)
#define ID_EDIT_3           (GUI_ID_USER + 0x40)
#define ID_EDIT_4           (GUI_ID_USER + 0x41)
#define ID_EDIT_5           (GUI_ID_USER + 0x42)
#define ID_EDIT_6           (GUI_ID_USER + 0x43)
#define ID_EDIT_7           (GUI_ID_USER + 0x44)
#define ID_EDIT_8           (GUI_ID_USER + 0x45)
#define ID_EDIT_9           (GUI_ID_USER + 0x46)
#define ID_EDIT_10           (GUI_ID_USER + 0x47)

// USER START (Optionally insert additional defines)

#define MAX_REG_NUM (0x14 + 1)

#define BQ_25895_NONE		0
#define BQ_25895_READ		1
#define BQ_25895_WRITE		2

WM_HWIN  hWinPMU = WM_HWIN_NULL;
unsigned char BQ25895_REG[MAX_REG_NUM];

TaskHandle_t  OS_BQ25895_task;
uint32_t g_bq_type;

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate_PMU[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 854, 430, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 20, 330, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 120, 330, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 220, 330, 50, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 290, 330, 50, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 384, 330, 80, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 20, 10, 280, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 5, 40, 170, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 5, 65, 170, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 5, 90, 170, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 5, 115, 170, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 5, 140, 170, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_6, 5, 165, 170, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_7, 5, 190, 170, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_8, 5, 215, 170, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_9, 5, 240, 170, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_10, 5, 265, 170, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_11, 5, 290, 170, 16, 0, 0x64, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 190, 40, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_1, 190, 65, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_2, 190, 90, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_3, 190, 115, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_4, 190, 140, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_5, 190, 167, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_6, 190, 190, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_7, 190, 215, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_8, 190, 240, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_9, 190, 265, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_10, 190, 290, 80, 18, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_12, 285, 40, 160, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_13, 285, 65, 160, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_14, 285, 90, 160, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_15, 285, 115, 160, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_16, 285, 140, 160, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_17, 285, 167, 160, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_18, 285, 190, 160, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_19, 285, 215, 160, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_20, 285, 240, 160, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_21, 285, 265, 160, 16, 0, 0x64, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_11, 460, 40, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_12, 460, 65, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_13, 460, 90, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_14, 460, 115, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_15, 460, 140, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_16, 460, 167, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_17, 460, 190, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_18, 460, 215, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_19, 460, 240, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_20, 460, 265, 80, 18, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_22, 560, 10, 130, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_23, 550, 40, 130, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_24, 550, 65, 130, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_25, 550, 90, 130, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_26, 550, 115, 130, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_27, 550, 140, 130, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_28, 550, 167, 130, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_29, 550, 190, 130, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_30, 550, 215, 130, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_31, 550, 240, 130, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_32, 550, 265, 130, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_33, 550, 290, 130, 16, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 695, 40, 130, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 695, 65, 130, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_2, 695, 90, 130, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_3, 695, 115, 130, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_4, 695, 140, 130, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_5, 695, 167, 130, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_6, 695, 190, 130, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_7, 695, 215, 130, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_8, 695, 240, 130, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_9, 695, 265, 130, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_10, 695, 290, 130, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};


/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

char *VBUS_STR[8] = {
	"No Input",
	"USB Host SOP",
	"USB CDP(1.5A)",
	"USB DCP(3.25A)",
	"MaxCharge(1.5A)",
	"UNKNOW DC",
	"NON-Standard DC",
	"OTG"
};
char *CHARGE_STA_STR[4] = {
	"Not Charging",
	"Pre-charge",
	"Fast Charging",
	"Charge Term Done"
};
char *POWER_GOOD_STR[2] = {
	"Not Power Good",
	"Power Good"
};
char *SDP_STA_STR[2] = {
	"USB100 input detected",
	"USB500 input detected"
};
char *VSYS_STA_STR[2] = {
	"Not in VSYSMIN reg",
	"In VSYSMIN reg"
};
char *THERM_STA_STR[2] = {
	"Normal",
	"In Thermal Reg"
};
char *VBUS_GOOD_STA_STR[2] = {
	"Not VBUS Attach",
	"VBUS Attached"
};
char *VDPM_STA_STR[2] = {
	"Not in VINDPM",
	"VINDPM"
};
char *IDPM_STA_STR[2] = {
	"Not in IINDPM",
	"IINDPM"
};
char *ICO_OPTIMIZED_STR[2] = {
	"in progress",
	"Max Cur Detected"
};
// USER START (Optionally insert additional static code)

void BQ25895_Update(WM_MESSAGE * pMsg)
{
	char temp_buf[40];
	WM_HWIN hWin = pMsg->hWin;
	// for (unsigned int i = 0, j = ID_TEXT_0; i <= MAX_REG_NUM; i++, j++) {
	// 	TEXT_SetFont(WM_GetDialogItem(hWin, j), GUI_FONT_16B_ASCII);
	// 	TEXT_SetTextAlign(WM_GetDialogItem(hWin, j), GUI_TA_LEFT | GUI_TA_VCENTER);
	// 	sprintf((char*)buf, "REG[%02X]: 0x%02X", i , BQ25895_REG[i]);
	// 	TEXT_SetText(WM_GetDialogItem(hWin, j), (char*)buf);
	// }
	{
		EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_0), VBUS_STR[(BQ25895_REG[0x0B]>>5)&0x07]);// REG 0x0B
		EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_1), CHARGE_STA_STR[(BQ25895_REG[0x0B]>>3)&0x03]);// REG 0x0B
		EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_2), POWER_GOOD_STR[(BQ25895_REG[0x0B]>>2)&0x01]);// REG 0x0B
		EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_3), SDP_STA_STR[(BQ25895_REG[0x0B]>>1)&0x01]);// REG 0x0B
		EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_4), VSYS_STA_STR[(BQ25895_REG[0x0B]>>0)&0x01]);// REG 0x0B
		EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_5), THERM_STA_STR[(BQ25895_REG[0x0E]>>7)&0x01]);// REG 0x0E
		EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_6), VBUS_GOOD_STA_STR[(BQ25895_REG[0x11]>>7)&0x01]);// REG 0x11
		EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_7), VDPM_STA_STR[(BQ25895_REG[0x13]>>7)&0x01]);// REG 0x13
		EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_8), IDPM_STA_STR[(BQ25895_REG[0x13]>>6)&0x01]);// REG 0x13
		sprintf((char*)temp_buf, "%d mV", 100 + (BQ25895_REG[0x00]&0x3F) * 50);
		EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_9), temp_buf);// REG 0x00
		EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_10), ICO_OPTIMIZED_STR[(BQ25895_REG[0x14]>>6)&0x01]);// REG 0x14
	}
}


// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog_PMU(WM_MESSAGE * pMsg) {
	int     NCode;
	int     Id;
	WM_HWIN hWin = pMsg->hWin;
	char temp_buf[24];
	switch (pMsg->MsgId) {
		case WM_INIT_DIALOG: {
			//初始化窗口标题
			{
				FRAMEWIN_SetClientColor(hWin,GUI_WHITE);//背景设置为黑色
				FRAMEWIN_SetTitleHeight(hWin, 32);
				FRAMEWIN_SetTextAlign(hWin, GUI_TA_HCENTER | GUI_TA_VCENTER);
				FRAMEWIN_SetText(hWin, "BQ25895");
				FRAMEWIN_SetFont(hWin, &GUI_FontHZ24);
			}
			//底部按键
			{
				BUTTON_SetFont(WM_GetDialogItem(hWin, ID_BUTTON_0), &GUI_FontHZ16);
				BUTTON_SetFont(WM_GetDialogItem(hWin, ID_BUTTON_1), &GUI_FontHZ16);
				BUTTON_SetFont(WM_GetDialogItem(hWin, ID_BUTTON_2), &GUI_FontHZ16);
				BUTTON_SetFont(WM_GetDialogItem(hWin, ID_BUTTON_3), &GUI_FontHZ16);
				BUTTON_SetFont(WM_GetDialogItem(hWin, ID_BUTTON_4), &GUI_FontHZ32);

				BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_0), "Load Reg");
				BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_1), "Save Reg");
				BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_2), "Read");
				BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_3), "Write");
				BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_4), "退出");
			}
			//文本部分
			{
				//标题一
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_0), "Multi-bit I2C Pulldown Menu");
				TEXT_SetFont(WM_GetDialogItem(hWin, ID_TEXT_0), GUI_FONT_20B_ASCII);
				TEXT_SetTextAlign(WM_GetDialogItem(hWin, ID_TEXT_0), GUI_TA_HCENTER | GUI_TA_VCENTER);
				//文本 第一列
				for (unsigned int j = ID_TEXT_1, i = 0; i <= (ID_TEXT_11 - ID_TEXT_1); i++, j++) {
					TEXT_SetFont(WM_GetDialogItem(hWin, j), GUI_FONT_16B_ASCII);
					TEXT_SetTextAlign(WM_GetDialogItem(hWin, j), GUI_TA_RIGHT | GUI_TA_VCENTER);
				}
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_1),  "Input Current Limit");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_2),  "Input Voltage Limit");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_3),  "Voltage DPM Offset");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_4),  "Minimum System Voltage");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_5),  "ADC Conversion Rate");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_6),  "Charge Voltage Limit");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_7),  "Pre-Charge Current Limit");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_8),  "Fast Charge Current Limit");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_9),  "Termination Current Limit");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_10), "IR Compensation Resistor");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_11), "IR Comp Voltage Clamp");
				//下拉列表控件 第一列
				for (unsigned int j = ID_DROPDOWN_0, i = 0; i <= (ID_DROPDOWN_10 - ID_DROPDOWN_0); i++, j++) {
					DROPDOWN_SetFont(WM_GetDialogItem(hWin, j), GUI_FONT_13_1);
					DROPDOWN_SetListHeight(WM_GetDialogItem(hWin, j), 65);
					DROPDOWN_SetAutoScroll(WM_GetDialogItem(hWin, j), 1); //滚动条开关
					// DROPDOWN_Expand(WM_GetDialogItem(hWin, j)); //打开列表  物理按键使用的
				}
				for (unsigned int i = 0; i <= 0x3F; i++) {
					// [ 0x00 ] input current limit
					// memset(temp_buf, 0, sizeof(temp_buf));
					sprintf((char*)temp_buf, "%d mA", (100 + i * 50));
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_0), (char*)temp_buf);
				}
				for (unsigned int i = 0; i <= 0x1F; i++) {
					// [ 0x01 ] input voltage limit
					// memset(temp_buf, 0, sizeof(temp_buf));
					sprintf((char*)temp_buf, "%d mV", (i * 100));
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_1), (char*)temp_buf);
				}
				for (unsigned int i = 0x0D; i <= 0x3F; i++) {
					// [ 0x0D ] VINDPM offset 
					// memset(temp_buf, 0, sizeof(temp_buf));
					sprintf((char*)temp_buf, "%3.1f V", (2.6f + (float)i * 0.1f));
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_2), (char*)temp_buf);
				}
				for (unsigned int i = 0; i <= 0x07; i++) {
					// [ 0x03 ] mini sys voltage 
					// memset(temp_buf, 0, sizeof(temp_buf));
					sprintf((char*)temp_buf, "%3.1f V", (3.0f + (float)i * 0.1f));
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_3), (char*)temp_buf);
				}
				// [ 0x02 ] ADC Conversion Rate
				{
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_4), "One Shot");
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_4), "1S Cont");
				}
				for (unsigned int i = 0; i <= 0x3F; i++) {
					// [ 0x06 ] charge voltage limit
					// memset(temp_buf, 0, sizeof(temp_buf));
					sprintf((char*)temp_buf, "%5.3f V", (3.840f + (float)i * 0.016f));
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_5), (char*)temp_buf);
				}
				for (unsigned int i = 0; i <= 0x0F; i++) {
					// [ 0x05 ] pre-charge current limit
					// memset(temp_buf, 0, sizeof(temp_buf));
					sprintf((char*)temp_buf, "%d mV", (64 + i * 64));
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_6), (char*)temp_buf);
				}
				for (unsigned int i = 0; i <= 0x7F; i++) {
					// [ 0x04 ] fast charge current limit
					// memset(temp_buf, 0, sizeof(temp_buf));
					sprintf((char*)temp_buf, "%d mV", (i * 64));
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_7), (char*)temp_buf);
				}
				for (unsigned int i = 0; i <= 0x0F; i++) {
					// [ 0x05 ] Termination Current Limit
					// memset(temp_buf, 0, sizeof(temp_buf));
					sprintf((char*)temp_buf, "%d mV", (64 + i * 64));
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_8), (char*)temp_buf);
				}
				for (unsigned int i = 0; i <= 0x07; i++) {
					// [ 0x08 ] IR Compensation Resistor Setting
					// memset(temp_buf, 0, sizeof(temp_buf));
					sprintf((char*)temp_buf, "%d mOhm", (i * 20));
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_9), (char*)temp_buf);
				}
				for (unsigned int i = 0; i <= 0x07; i++) {
					// [ 0x08 ] IR Compensation Voltage Clamp
					// memset(temp_buf, 0, sizeof(temp_buf));
					sprintf((char*)temp_buf, "%d mV", (i * 32));
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_10), (char*)temp_buf);
				}
				//标题一 第二列
				for (unsigned int j = ID_TEXT_12, i = 0; i <= (ID_TEXT_21 - ID_TEXT_12); i++, j++) {
					TEXT_SetFont(WM_GetDialogItem(hWin, j), GUI_FONT_16B_ASCII);
					TEXT_SetTextAlign(WM_GetDialogItem(hWin, j), GUI_TA_RIGHT | GUI_TA_VCENTER);
				}
				//文本 第二列
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_12), "Boost TS Hot Monitor");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_13), "Boost TS Cold Monitor");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_14), "Boost Frequency");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_15), "Boost Voltage Control");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_16), "Boost Current Limit");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_17), "Battery LowV");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_18), "Recharge threshold");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_19), "WatchDog Timer");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_20), "Fast Charge Timer");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_21), "Thermal Reg. Threshold");
				//下拉列表控件 第一列
				for (unsigned int j = ID_DROPDOWN_11, i = 0; i <= (ID_DROPDOWN_20 - ID_DROPDOWN_11); i++, j++) {
					DROPDOWN_SetFont(WM_GetDialogItem(hWin, j), GUI_FONT_13_1);
					DROPDOWN_SetListHeight(WM_GetDialogItem(hWin, j), 65);
					DROPDOWN_SetAutoScroll(WM_GetDialogItem(hWin, j), 1); //滚动条开关
					// DROPDOWN_Expand(WM_GetDialogItem(hWin, j)); //打开列表  物理按键使用的
				}
				{
					// [ 0x01 ] Boost Mode Hot Temperature Monitor Threshold
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_11), "34.75%");
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_11), "37.75%");
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_11), "31.25%");
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_11), "Disable");
				}
				{
					// [ 0x01 ] Boost Mode Cold Temperature Monitor Threshold
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_12), "77%");
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_12), "80%");
				}
				{
					// [ 0x02 ] Boost Mode Frequency Selection
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_13), "1.5 MHz");
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_13), "500 KHz");
				}
				for (unsigned int i = 0; i <= 0x0F; i++) {
					// [ 0x0A ] Boost Mode Voltage Regulation
					// memset(temp_buf, 0, sizeof(temp_buf));
					sprintf((char*)temp_buf, "%3.1f V", (4.550f + (float)i * 0.064f));
					DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_14), (char*)temp_buf);
				}
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_15), "1.3 A");
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_16), "3.0 V");

				// [ 0x06 ] Battery Recharge Threshold Offset
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_17), "100 mV");
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_17), "200 mV");
				// [ 0x07 ] I2C Watchdog Timer Setting
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_18), "Disable");
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_18), "40S");
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_18), "80S");
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_18), "160S");
				// [ 0x07 ] Fast Charge Timer Setting
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_19), "5 hrs");
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_19), "8 hrs");
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_19), "12 hrs");
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_19), "20 hrs");
				// [ 0X08 ] Thermal Regulation Threshold
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_20), "60 C");
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_20), "80 C");
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_20), "100 C");
				DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_DROPDOWN_20), "120 C");
			}
			{
				//标题二
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_22), "Status");
				TEXT_SetFont(WM_GetDialogItem(hWin, ID_TEXT_22), GUI_FONT_20B_ASCII);
				TEXT_SetTextAlign(WM_GetDialogItem(hWin, ID_TEXT_22), GUI_TA_HCENTER | GUI_TA_VCENTER);
				//文本 第一列
				for (unsigned int j = ID_TEXT_23, i = 0; i <= (ID_TEXT_33 - ID_TEXT_23); i++, j++) {
					TEXT_SetFont(WM_GetDialogItem(hWin, j), GUI_FONT_16B_ASCII);
					TEXT_SetTextAlign(WM_GetDialogItem(hWin, j), GUI_TA_RIGHT | GUI_TA_VCENTER);
				}
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_23), "VBUS");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_24), "Charge State");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_25), "POWER GOOD");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_26), "SDP");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_27), "VSYS");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_28), "Thermal Reg Status");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_29), "VBUS Good");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_30), "VINDPM Status");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_31), "IINDPM Status");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_32), "Input Current Limit");
				TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_33), "ICD Optimized");
				//可编辑文本框
				for (unsigned int j = ID_EDIT_0, i = 0; i <= (ID_EDIT_10 - ID_EDIT_0); i++, j++) {
					EDIT_SetFont(WM_GetDialogItem(hWin, j), GUI_FONT_16B_ASCII);
					EDIT_SetTextAlign(WM_GetDialogItem(hWin, j), GUI_TA_LEFT | GUI_TA_VCENTER);
					EDIT_SetTextColor(WM_GetDialogItem(hWin, j), EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00FD020F));
					EDIT_SetInsertMode(WM_GetDialogItem(hWin, j), 0); //禁用插入模式
				}

				EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_0), VBUS_STR[0]);// REG 0x0B
				EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_1), CHARGE_STA_STR[0]);// REG 0x0B
				EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_2), POWER_GOOD_STR[0]);// REG 0x0B
				EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_3), SDP_STA_STR[0]);// REG 0x0B
				EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_4), VSYS_STA_STR[0]);// REG 0x0B
				EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_5), THERM_STA_STR[0]);// REG 0x0E
				EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_6), VBUS_GOOD_STA_STR[0]);// REG 0x11
				EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_7), VDPM_STA_STR[0]);// REG 0x13
				EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_8), IDPM_STA_STR[0]);// REG 0x13
				EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_9), "100 mV");// REG 0x00
				EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_10), ICO_OPTIMIZED_STR[0]);// REG 0x14
			}
		} break;

		case WM_NOTIFY_PARENT: {
			Id    = WM_GetId(pMsg->hWinSrc);
			NCode = pMsg->Data.v;
			switch(Id) {
				case ID_BUTTON_0: { // Notifications sent by 'Button'
				} break;

				case ID_BUTTON_1: { // Notifications sent by 'Button'
				} break;

				case ID_BUTTON_2: { // Notifications sent by 'Button'
					g_bq_type = BQ_25895_READ;
				} break;

				case ID_BUTTON_3: { // Notifications sent by 'Button'
				} break;

				case ID_BUTTON_4: { // Notifications sent by 'Button'
					if(NCode == WM_NOTIFICATION_RELEASED) {
						WM_MESSAGE Message;
						Message.hWinSrc = hWinPMU;
						Message.MsgId   = WM_DELETE;
						Message.Data.v  = 7;
						WM_SendMessage(hWinStatus, &Message);
						vTaskDelete(OS_BQ25895_task);//删除任务
						// GUI_EndDialog(pMsg->hWin, 0); //删除窗口
						WM_DeleteWindow(hWinPMU);
						hWinPMU = NULL;
					}
				} break;
			}
		} break;

		case MSG_BQ25895: {
			BQ25895_Update(pMsg);
		} break;

		default: {
			WM_DefaultProc(pMsg);
		} break;
	}
}

void BQ25895_Task(void *pvParameters)
{
	TickType_t    xLastWakeTime;
	//初始化当前心跳，随后由vTaskDelayUntil自动更新
	xLastWakeTime = xTaskGetTickCount();
	while(1)
	{
		for(int i = 0; i < MAX_REG_NUM; i++) {
			bq2589x_read_byte(&BQ25895_REG[i], i);
		}
		if (g_bq_type == BQ_25895_READ) {
			g_bq_type = 0;
			WM_SendMessageNoPara(WM_GetClientWindow(hWinPMU), MSG_BQ25895);
		}
		vTaskDelayUntil(&xLastWakeTime, configTICK_RATE_HZ/10);
	}
}

void APP_PMUDLG(WM_HWIN hWin, uint32_t idenx) {
    WM_MESSAGE Message;
    if(hWinPMU == NULL) {
		//创建对话框
		hWinPMU = GUI_CreateDialogBox(  _aDialogCreate_PMU,
										GUI_COUNTOF(_aDialogCreate_PMU),
										_cbDialog_PMU,
										hWin,
										0,
										0);

        xTaskCreate(BQ25895_Task, "BQ25895_Task", 512 /sizeof(uint32_t), NULL, 4, &OS_BQ25895_task);
		Message.hWinSrc = hWinPMU;
		Message.MsgId   = WM_CREATE;
		Message.Data.v  = idenx;
		WM_SendMessage(hWinStatus, &Message);
		PRINTF("App_PMU_BQ25895 idenx = %d  src= 0x%x \r\n", idenx, hWinPMU);
	} else {
		WM_ShowWindow(hWinPMU);
	}
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
